query campaings($withSection: Boolean = false, $withAllCollected: Boolean = false, $withLast5daysCollectedBySection: Boolean = false){
  campaings {
    id
    year
    month
    barn {
      id
      name
    }
    sections @include(if: $withSection){
      id
      name
      collects {
        id
        quantity
      }      
    }
    last5daysCollectedBySection @include(if: $withLast5daysCollectedBySection) {
      sectionName
      values {
        date
        quantity
      }
    }
    allCollected @include(if: $withAllCollected) {
      date
      quantity
    }
  }
}