query getSection($id: ID!, $datetime: String) {
  section(id: $id, datetime: $datetime) {
    id
    name
    collects {
      id
      quantity
      datetime
    }
    deads {
      id
      quantity
      datetime
    }      
  }
}